### PR TITLE
Improve code readability

### PR DESCRIPTION
**Pull request by luigibrancati**
Hi, I wanted to contribute to the project and started here by attempting to improved the code readability.

Here I attempted to improve the C++ code readability by using enums and converting some global function to struct methods. I also defined some operators for Card and Hand which will come in handy when comparing them. I will probably do another PR with more changes later.

I also switched the testing framework from unittest to pytest, which is much easier to use in my opinion, and added some tests to avoid regression while working on the code.
You can easily run them by installing pytest with `pip install pytest==7.2.1` and running `pytest` inside the `PokerPy` root folder.

### CODE REVIEW

**Comment by glpcc** [comment]
Hi, I like the changes you made, I still have to check if the performance is maintained but with a quick view of the changes i dont think it did. 
On the other hand, I have to ask you to revert the changes in the python interface. I think that Cards should be created with a string like "KD" which much more user friendly than using ints, and the hand_type of a hand should be a string instead of an int.
I you apply those changes into your pull request I will for sure accept the pull request.

**Comment by glpcc** [comment]
Perfect, only a minor detail and I will accept the PR. The hand_type property should be a string not just that it can be created with a string, i.e, if you acces hand_example.hand_type it should return a string.

**Comment by luigibrancati** [comment]
Hi, thanks for your feedback. Of course, the last word is yours, so let me just share the reason behind some of the changes in this PR. Also note I recently pushed some more commits.

In general, the interface you want to expose to the user shouldn't hinder the code that actually does the calculations. My opinion is that the internal representation of `Hand` and `Card` should rely solely on numeric types like `enum`, but you can still have a string-based user interface that converts the numbers to/from a string when it's necessary. For example, having `hand_type` as a string means you have to convert it to an integer and store it as a new variable everytime you want to actually use it. A better pattern is to store it like an `int` or `enum` so that you can readily use it in calculations, and then converting it to/from string only when necessary, i.e. when a user wants to create a new instance or when you want to print it.

So, to have an easier interface, so I just added custom C++ constructors for `Card` and `Hand` and added them to pybind, you can check the `test_cards.py` and `test_hands.py` modules to see how that works. Now users have both options, i.e. instantiating with integers or strings.

Let me know if I addressed the problem.

**Comment by glpcc** [comment]
Yes, I completely agree with you with the representation of hands and cards inside cpp, I just wanted to change the setter and getter of the hand_type property so that it returns the string associated with the number stored inside cpp, so that in the python interface the hand_type property is always a string.

**Comment by luigibrancati** [comment]
I modified the setter and getter for both `suit` inside `Card` and `hand_type` inside `Hand`. The `suit` uses symbols like `♣`. Let me know what you think.

**Comment by glpcc** [comment]
Perfect should we also do the same with the card value, so that it returns 'A' instead of 13 in case of an ace or not? , I think that given that the operators are alredy made it would improve the python interface, let me know what you think. As soon as we decide on this matter i would accept the PR. Thanks for contributing.

**Comment by luigibrancati** [comment]
I think that's a good idea, will try to implement that later

**Comment by glpcc** [comment]
Perfect I will accept the pull rquest and try to change the docs during this weekend, thanks!

**Pull request merged**
